webtalk_init -webtalk_dir D:/Software/Xilinx/Projects/RC5_Complete_Module/RC5_Complete_Module.sim/sim_1/behav/xsim/xsim.dir/RC5_TestBench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Nov 12 13:30:46 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3286242" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "82f5f3dc-9570-40ae-b7c0-89c8ee74a8ac" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "afb584096c9a49bd8534916cedbe9a58" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "61" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1382 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "38 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7716_KB" -context "xsim\\usage"
webtalk_transmit -clientid 760616008 -regid "" -xml D:/Software/Xilinx/Projects/RC5_Complete_Module/RC5_Complete_Module.sim/sim_1/behav/xsim/xsim.dir/RC5_TestBench_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Software/Xilinx/Projects/RC5_Complete_Module/RC5_Complete_Module.sim/sim_1/behav/xsim/xsim.dir/RC5_TestBench_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Software/Xilinx/Projects/RC5_Complete_Module/RC5_Complete_Module.sim/sim_1/behav/xsim/xsim.dir/RC5_TestBench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
